//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CartStatus
    {
        public int cartstatusId { get; set; }
        public string cartstatus { get; set; }
    }
}
